### PR TITLE
clang-tidy: fix warnings introduced in version 19

### LINKED ISSUE #153: cland-tidy-19 warnings on Bitcoin Core CI
From https://api.cirrus-ci.com/v1/task/5153787565834240/logs/ci.log:
```
[10:01:13.083] [315/704][22.3s] clang-tidy-19 -p=/ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu -quiet -load=/tidy-build/libbitcoin-tidy.so /ci_container_base/src/ipc/libmultiprocess/src/mp/gen.cpp
[10:01:13.083] /ci_container_base/src/ipc/libmultiprocess/src/mp/gen.cpp:217:5: warning: use a ranges version of this algorithm [modernize-use-ranges]
[10:01:13.083]   217 |     std::transform(guard.begin(), guard.end(), guard.begin(), [](unsigned char c) -> unsigned char {
[10:01:13.083]       |     ^~~~~~~~~~~~~~ ~~~~~~~~~~~~~  ~~~~~~~~~~~
[10:01:13.083]       |     std::ranges::transform guard
...
[10:04:02.737] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:109:5: warning: Address of stack memory associated with temporary object of type '(lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:109:51)' is still referred to by a temporary object on the stack upon returning to the caller.  This will be a dangling reference [clang-analyzer-core.StackAddressEscape]
[10:04:02.737]   109 |     return ReadDestEmplace{TypeList<LocalType>(), [&](auto&&... args) -> decltype(auto) {
[10:04:02.737]       |     ^
[10:04:02.737] /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/ipc/libmultiprocess/test/mp/test/foo.capnp.proxy-server.c++:41:12: note: Calling 'serverInvoke<mp::ProxyServer<mp::test::messages::FooInterface>, capnp::CallContext<mp::test::messages::FooInterface::PassCustomParams, mp::test::messages::FooInterface::PassCustomResults>, mp::ServerField<1, mp::Accessor<mp::foo_fields::Arg, 17>, mp::ServerRet<mp::Accessor<mp::foo_fields::Result, 18>, mp::ServerCall>>>'
[10:04:02.737]    41 |     return serverInvoke(*this, call_context, MakeServerField<1, Accessor<foo_fields::Arg, FIELD_IN | FIELD_BOXED>>(Make<ServerRet, Accessor<foo_fields::Result, FIELD_OUT | FIELD_BOXED>>(ServerCall())));
[10:04:02.737]       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.737] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:699:16: note: Calling 'ReplaceVoid<(lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:699:28), (lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:700:13)>'
[10:04:02.737]   699 |         return ReplaceVoid([&]() { return fn.invoke(server_context, ArgList()); },
[10:04:02.737]       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.737]   700 |             [&]() { return kj::Promise<CallContext>(kj::mv(call_context)); })
[10:04:02.737]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.737] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:656:5: note: Calling 'operator()'
[10:04:02.737]   656 |     fn();
[10:04:02.737]       |     ^~~~
[10:04:02.737] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:699:43: note: Calling 'ServerField::invoke'
[10:04:02.737]   699 |         return ReplaceVoid([&]() { return fn.invoke(server_context, ArgList()); },
[10:04:02.737]       |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.737] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:529:16: note: Calling 'PassField<mp::Accessor<mp::foo_fields::Arg, 17>, mp::test::FooCustom, mp::ServerInvokeContext<mp::ProxyServer<mp::test::messages::FooInterface>, capnp::CallContext<mp::test::messages::FooInterface::PassCustomParams, mp::test::messages::FooInterface::PassCustomResults>>, const mp::ServerRet<mp::Accessor<mp::foo_fields::Result, 18>, mp::ServerCall> &, mp::TypeList<>>'
[10:04:02.737]   529 |         return PassField<Accessor>(Priority<2>(),
[10:04:02.737]       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.737]   530 |             typename Split<argc, ArgTypes>::First(),
[10:04:02.737]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.737]   531 |             server_context,
[10:04:02.737]       |             ~~~~~~~~~~~~~~~
[10:04:02.737]   532 |             this->parent(),
[10:04:02.738]       |             ~~~~~~~~~~~~~~~
[10:04:02.738]   533 |             typename Split<argc, ArgTypes>::Second(),
[10:04:02.738]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   534 |             std::forward<Args>(args)...);
[10:04:02.738]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:272:5: note: Calling 'MaybeReadField<mp::TypeList<mp::test::FooCustom>, mp::InvokeContext &, mp::StructField<mp::Accessor<mp::foo_fields::Arg, 17>, const mp::test::messages::FooInterface::PassCustomParams::Reader>, mp::ReadDestEmplace<mp::test::FooCustom, (lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:273:83)>>'
[10:04:02.738]   272 |     MaybeReadField(std::integral_constant<bool, Accessor::in>(), TypeList<ArgType>(), invoke_context,
[10:04:02.738]       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   273 |         Make<StructField, Accessor>(params), ReadDestEmplace(TypeList<ArgType>(), [&](auto&&... args) -> auto& {
[10:04:02.738]       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   274 |             param.emplace(std::forward<decltype(args)>(args)...);
[10:04:02.738]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   275 |             return *param;
[10:04:02.738]       |             ~~~~~~~~~~~~~~
[10:04:02.738]   276 |         }));
[10:04:02.738]       |         ~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:244:5: note: Calling 'ReadField<mp::test::FooCustom, mp::InvokeContext &, mp::StructField<mp::Accessor<mp::foo_fields::Arg, 17>, const mp::test::messages::FooInterface::PassCustomParams::Reader>, mp::ReadDestEmplace<mp::test::FooCustom, (lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:273:83)>>'
[10:04:02.738]   244 |     ReadField(std::forward<Args>(args)...);
[10:04:02.738]       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:147:12: note: Calling 'CustomReadField<mp::StructField<mp::Accessor<mp::foo_fields::Arg, 17>, const mp::test::messages::FooInterface::PassCustomParams::Reader>, mp::ReadDestEmplace<mp::test::FooCustom, (lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:273:83)>>'
[10:04:02.738]   147 |     return CustomReadField(TypeList<RemoveCvRef<LocalTypes>...>(), Priority<2>(), std::forward<Args>(args)...);
[10:04:02.738]       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/test/mp/test/foo-types.h:35:12: note: Calling 'ReadDestEmplace::update'
[10:04:02.738]    35 |     return read_dest.update([&](FooCustom& value) {
[10:04:02.738]       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]    36 |         value.v1 = ReadField(TypeList<std::string>(), invoke_context, mp::Make<mp::ValueField>(custom.getV1()), ReadDestTemp<std::string>());
[10:04:02.738]       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]    37 |         value.v2 = custom.getV2();
[10:04:02.738]       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]    38 |     });
[10:04:02.738]       |     ~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:87:23: note: 'is_const_v' is false
[10:04:02.738]    87 |         if constexpr (std::is_const_v<std::remove_reference_t<std::invoke_result_t<EmplaceFn>>>) {
[10:04:02.738]       |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:87:9: note: Taking false branch
[10:04:02.738]    87 |         if constexpr (std::is_const_v<std::remove_reference_t<std::invoke_result_t<EmplaceFn>>>) {
[10:04:02.738]       |         ^
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:97:13: note: Calling 'operator()'
[10:04:02.738]    97 |             update_fn(temp);
[10:04:02.738]       |             ^~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/test/mp/test/foo-types.h:36:113: note: Calling 'ReadDestTemp<std::basic_string<char>>'
[10:04:02.738]    36 |         value.v1 = ReadField(TypeList<std::string>(), invoke_context, mp::Make<mp::ValueField>(custom.getV1()), ReadDestTemp<std::string>());
[10:04:02.738]       |                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:109:5: note: Address of stack memory associated with temporary object of type '(lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:109:51)' is still referred to by a temporary object on the stack upon returning to the caller.  This will be a dangling reference
[10:04:02.738]   109 |     return ReadDestEmplace{TypeList<LocalType>(), [&](auto&&... args) -> decltype(auto) {
[10:04:02.738]       |     ^                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   110 |         return LocalType{std::forward<decltype(args)>(args)...};
[10:04:02.738]       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   111 |     }};
[10:04:02.738]       |     ~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/type-number.h:55:32: warning: The value '0' provided to the cast expression is not in the valid range of values for 'FooEnum' [clang-analyzer-optin.core.EnumCastOutOfRange]
[10:04:02.738]    55 |     return read_dest.construct(static_cast<LocalType>(input.get()));
[10:04:02.738]       |                                ^
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/test/mp/test/foo.h:24:12: note: enum declared here
[10:04:02.738]    24 | enum class FooEnum : uint8_t { ONE = 1, TWO = 2, };
[10:04:02.738]       | ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/ipc/libmultiprocess/test/mp/test/foo.capnp.proxy-server.c++:53:12: note: Calling 'serverInvoke<mp::ProxyServer<mp::test::messages::FooInterface>, capnp::CallContext<mp::test::messages::FooInterface::PassEnumParams, mp::test::messages::FooInterface::PassEnumResults>, mp::ServerField<1, mp::Accessor<mp::foo_fields::Arg, 1>, mp::ServerRet<mp::Accessor<mp::foo_fields::Result, 2>, mp::ServerCall>>>'
[10:04:02.738]    53 |     return serverInvoke(*this, call_context, MakeServerField<1, Accessor<foo_fields::Arg, FIELD_IN>>(Make<ServerRet, Accessor<foo_fields::Result, FIELD_OUT>>(ServerCall())));
[10:04:02.738]       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:699:16: note: Calling 'ReplaceVoid<(lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:699:28), (lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:700:13)>'
[10:04:02.738]   699 |         return ReplaceVoid([&]() { return fn.invoke(server_context, ArgList()); },
[10:04:02.738]       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   700 |             [&]() { return kj::Promise<CallContext>(kj::mv(call_context)); })
[10:04:02.738]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:656:5: note: Calling 'operator()'
[10:04:02.738]   656 |     fn();
[10:04:02.738]       |     ^~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:699:43: note: Calling 'ServerField::invoke'
[10:04:02.738]   699 |         return ReplaceVoid([&]() { return fn.invoke(server_context, ArgList()); },
[10:04:02.738]       |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:529:16: note: Calling 'PassField<mp::Accessor<mp::foo_fields::Arg, 1>, mp::test::FooEnum, mp::ServerInvokeContext<mp::ProxyServer<mp::test::messages::FooInterface>, capnp::CallContext<mp::test::messages::FooInterface::PassEnumParams, mp::test::messages::FooInterface::PassEnumResults>>, const mp::ServerRet<mp::Accessor<mp::foo_fields::Result, 2>, mp::ServerCall> &, mp::TypeList<>>'
[10:04:02.738]   529 |         return PassField<Accessor>(Priority<2>(),
[10:04:02.738]       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   530 |             typename Split<argc, ArgTypes>::First(),
[10:04:02.738]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   531 |             server_context,
[10:04:02.738]       |             ~~~~~~~~~~~~~~~
[10:04:02.738]   532 |             this->parent(),
[10:04:02.738]       |             ~~~~~~~~~~~~~~~
[10:04:02.738]   533 |             typename Split<argc, ArgTypes>::Second(),
[10:04:02.738]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   534 |             std::forward<Args>(args)...);
[10:04:02.738]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:272:5: note: Calling 'MaybeReadField<mp::TypeList<mp::test::FooEnum>, mp::InvokeContext &, mp::StructField<mp::Accessor<mp::foo_fields::Arg, 1>, const mp::test::messages::FooInterface::PassEnumParams::Reader>, mp::ReadDestEmplace<mp::test::FooEnum, (lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:273:83)>>'
[10:04:02.738]   272 |     MaybeReadField(std::integral_constant<bool, Accessor::in>(), TypeList<ArgType>(), invoke_context,
[10:04:02.738]       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   273 |         Make<StructField, Accessor>(params), ReadDestEmplace(TypeList<ArgType>(), [&](auto&&... args) -> auto& {
[10:04:02.738]       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   274 |             param.emplace(std::forward<decltype(args)>(args)...);
[10:04:02.738]       |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]   275 |             return *param;
[10:04:02.738]       |             ~~~~~~~~~~~~~~
[10:04:02.738]   276 |         }));
[10:04:02.738]       |         ~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:244:5: note: Calling 'ReadField<mp::test::FooEnum, mp::InvokeContext &, mp::StructField<mp::Accessor<mp::foo_fields::Arg, 1>, const mp::test::messages::FooInterface::PassEnumParams::Reader>, mp::ReadDestEmplace<mp::test::FooEnum, (lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:273:83)>>'
[10:04:02.738]   244 |     ReadField(std::forward<Args>(args)...);
[10:04:02.738]       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:147:12: note: Calling 'CustomReadField<mp::test::FooEnum, mp::StructField<mp::Accessor<mp::foo_fields::Arg, 1>, const mp::test::messages::FooInterface::PassEnumParams::Reader>, mp::ReadDestEmplace<mp::test::FooEnum, (lambda at /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:273:83)>>'
[10:04:02.738]   147 |     return CustomReadField(TypeList<RemoveCvRef<LocalTypes>...>(), Priority<2>(), std::forward<Args>(args)...);
[10:04:02.738]       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/type-number.h:55:55: note: Calling 'StructField::get'
[10:04:02.738]    55 |     return read_dest.construct(static_cast<LocalType>(input.get()));
[10:04:02.738]       |                                                       ^~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:41:99: note: Calling 'Arg::get'
[10:04:02.738]    41 |     template<typename A = Accessor> auto get() const -> decltype(A::get(this->m_struct)) { return A::get(this->m_struct); }
[10:04:02.738]       |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/ipc/libmultiprocess/test/mp/test/foo.capnp.proxy.h:174:82: note: Calling 'Reader::getArg'
[10:04:02.738]   174 |     template<typename S> static auto get(S&& s) -> decltype(s.getArg()) { return s.getArg(); }
[10:04:02.738]       |                                                                                  ^~~~~~~~~~
[10:04:02.738] /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/ipc/libmultiprocess/test/mp/test/foo.capnp.h:5998:10: note: Calling 'StructReader::getDataField'
[10:04:02.738]  5998 |   return _reader.getDataField< ::int32_t>(
[10:04:02.738]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]  5999 |       ::capnp::bounded<0>() * ::capnp::ELEMENTS);
[10:04:02.738]       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /usr/include/capnp/layout.h:1099:7: note: Assuming the condition is false
[10:04:02.738]  1099 |   if ((offset + ONE * ELEMENTS) * capnp::bitsPerElement<T>() <= dataSize) {
[10:04:02.738]       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /usr/include/capnp/layout.h:1099:3: note: Taking false branch
[10:04:02.738]  1099 |   if ((offset + ONE * ELEMENTS) * capnp::bitsPerElement<T>() <= dataSize) {
[10:04:02.738]       |   ^
[10:04:02.738] /usr/include/capnp/layout.h:1102:5: note: Returning zero
[10:04:02.738]  1102 |     return static_cast<T>(0);
[10:04:02.738]       |     ^~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/ipc/libmultiprocess/test/mp/test/foo.capnp.h:5998:10: note: Returning from 'StructReader::getDataField'
[10:04:02.738]  5998 |   return _reader.getDataField< ::int32_t>(
[10:04:02.738]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]  5999 |       ::capnp::bounded<0>() * ::capnp::ELEMENTS);
[10:04:02.738]       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/ipc/libmultiprocess/test/mp/test/foo.capnp.h:5998:3: note: Returning zero
[10:04:02.738]  5998 |   return _reader.getDataField< ::int32_t>(
[10:04:02.738]       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738]  5999 |       ::capnp::bounded<0>() * ::capnp::ELEMENTS);
[10:04:02.738]       |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/ipc/libmultiprocess/test/mp/test/foo.capnp.proxy.h:174:82: note: Returning from 'Reader::getArg'
[10:04:02.738]   174 |     template<typename S> static auto get(S&& s) -> decltype(s.getArg()) { return s.getArg(); }
[10:04:02.738]       |                                                                                  ^~~~~~~~~~
[10:04:02.738] /ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/src/ipc/libmultiprocess/test/mp/test/foo.capnp.proxy.h:174:75: note: Returning zero
[10:04:02.738]   174 |     template<typename S> static auto get(S&& s) -> decltype(s.getArg()) { return s.getArg(); }
[10:04:02.738]       |                                                                           ^~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:41:99: note: Returning from 'Arg::get'
[10:04:02.738]    41 |     template<typename A = Accessor> auto get() const -> decltype(A::get(this->m_struct)) { return A::get(this->m_struct); }
[10:04:02.738]       |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/proxy-types.h:41:92: note: Returning zero
[10:04:02.738]    41 |     template<typename A = Accessor> auto get() const -> decltype(A::get(this->m_struct)) { return A::get(this->m_struct); }
[10:04:02.738]       |                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/type-number.h:55:55: note: Returning from 'StructField::get'
[10:04:02.738]    55 |     return read_dest.construct(static_cast<LocalType>(input.get()));
[10:04:02.738]       |                                                       ^~~~~~~~~~~
[10:04:02.738] /ci_container_base/src/ipc/libmultiprocess/include/mp/type-number.h:55:32: note: The value '0' provided to the cast expression is not in the valid range of values for 'FooEnum'
[10:04:02.738]    55 |     return read_dest.construct(static_cast<LocalType>(input.get()));
[10:04:02.738]       |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[10:05:00.005] 2 warnings generated.
```

### PR DESCRIPTION
**Pull request by purpleKarrot**
Should fix #153.

### CODE REVIEW

File: include/mp/proxy-types.h [hunk 1]
```diff
@@ -39,17 +39,17 @@ struct StructField
...
     template<typename A = Accessor, typename... Args> decltype(auto) set(Args&&... args) const { return A::set(this->m_struct, std::forward<Args>(args)...); }
     template<typename A = Accessor, typename... Args> decltype(auto) init(Args&&... args) const { return A::init(this->m_struct, std::forward<Args>(args)...); }
-    template<typename A = Accessor> auto setHas() const -> std::enable_if_t<A::optional> { return A::setHas(m_struct); }
-    template<typename A = Accessor> auto setHas() const -> std::enable_if_t<!A::optional> { }
-    template<typename A = Accessor> auto setWant() const -> std::enable_if_t<A::requested> { return A::setWant(m_struct); }
-    template<typename A = Accessor> auto setWant() const -> std::enable_if_t<!A::requested> { }
+    template<typename A = Accessor> void setHas() const requires(A::optional) { return A::setHas(m_struct); }
+    template<typename A = Accessor> void setHas() const requires(!A::optional) { }
+    template<typename A = Accessor> void setWant() const requires(A::requested) { return A::setWant(m_struct); }
+    template<typename A = Accessor> void setWant() const requires(!A::requested) { }
```
Comment (purpleKarrot) [inline include/mp/proxy-types.h:52]: Actually, they all should use `if constexpr`.

**Comment by purpleKarrot** [comment]
I think the remaining uses of SFINAE should be refactored rather than migrated to `requires`.

**Comment by ryanofsky** [comment]
Thanks for the changes! Didn't review in detail yet but these all look good.

> I think the remaining uses of SFINAE should be refactored rather than migrated to `requires`.

This probably makes sense but sounds vague. Do you have an example in mind which would make it clear?

**Comment by ryanofsky** [comment]
> After further analysis of the code, understood that all it does is unpack a tuple.

Yep, this code was only written this way to work when Bitcoin core was using c++11. Now it can be much simpler and 36898dbfc72c9748f54bf79f18d1ad6485f48920 seems right. This also looks like a nice change because it is declaring more explicit types (which would have been possible with c++11 too).

**Comment by hebasto** [comment]
Concept ACK.

File: include/mp/proxy-types.h [hunk 2]
```diff
@@ -389,30 +389,17 @@ struct ClientParam
...
-        auto callBuild(ClientInvokeContext& invoke_context, Params& params, ParamList, Values&&... values) ->
-            std::enable_if_t<(I == sizeof...(Types))>
+        template <typename Params, typename ParamList>
+        void handleField(ClientInvokeContext& invoke_context, Params& params, ParamList)
         {
-            MaybeBuildField(std::integral_constant<bool, Accessor::in>(), ParamList(), invoke_context,
-                Make<StructField, Accessor>(params), std::forward<Values>(values)...);
-            MaybeSetWant(
-                ParamList(), Priority<1>(), std::forward<Values>(values)..., Make<StructField, Accessor>(params));
+            auto const fun = [&]<typename... Values>(Values&&... values) {
```
Comment (ryanofsky) [inline include/mp/proxy-types.h:395]: In commit "replace custom tuple unpacking code with `std::apply`" (36898dbfc72c9748f54bf79f18d1ad6485f48920)

I think this code might be more straightforward and easier to review if this got rid of the `fun` variables and just passed the lambda directly as the first argument to std::apply. That way the indentation of the code inside the lambda would not have to change and the diff would be smaller and more obvious, and the resulting code would also be shorter.

File: include/mp/proxy-types.h [hunk 3]
```diff
@@ -421,24 +408,15 @@ struct ClientParam
...
-        }
-
-        template <int I, typename... Args>
-        auto callRead(Args&&... args) -> std::enable_if_t<(I < sizeof...(Types))>
+        template <typename Results, typename... Params>
+        void handleField(ClientInvokeContext& invoke_context, Results& results, TypeList<Params...>)
         {
-            callRead<I + 1>(std::forward<Args>(args)..., std::get<I>(m_client_param->m_values));
-        }
+            auto const fun = [&]<typename... Values>(Values&&... values) {
```
Comment (ryanofsky) [inline include/mp/proxy-types.h:414]: In commit "replace custom tuple unpacking code with `std::apply`" (36898dbfc72c9748f54bf79f18d1ad6485f48920)

Note: `Values` type here is currently unused, so lambda declaration could be simplified to just take an `auto&& values` parameter. However, keeping `Values` is nice even though it is unused because it makes ReadParams and BuildResults code more consistent. Also it might be useful to add perfect forwarding for `ReadDestUpdate(std::forward<Values>(values))` in the future. That will require other changes to this code however, so better to leave alone for now.

In general there are a **lot** more simplifications that can be made here now that this code no longer needs to work with c++11. Would be good to follow up in a separate PR.

File: src/mp/gen.cpp [hunk 4]
```diff
@@ -215,7 +215,7 @@ static void Generate(kj::StringPtr src_prefix,
     cpp_types << "namespace mp {\n";
 
     std::string guard = output_path;
-    std::transform(guard.begin(), guard.end(), guard.begin(), [](unsigned char c) -> unsigned char {
+    std::ranges::transform(guard, guard.begin(), [](unsigned char c) -> unsigned char {
```
Comment (ryanofsky) [inline src/mp/gen.cpp:218]: In commit "use ranges transform" (049d93113f27aca50381028e082c5538c0b1c574)

It's not really clear why this new code is better here. Would be good to have some explanation or note what the warning is in the commit message.

**Review by ryanofsky — APPROVED** [review]
Code review ACK 049d93113f27aca50381028e082c5538c0b1c574. Thanks for the fixes! This looks good in current form, but if interested in making improvements would suggest:

- Including linter error messages in commit messages so it is clear what is motivating the changes.
- Getting rid of `fun` variables in 36898dbfc72c9748f54bf79f18d1ad6485f48920 so fewer lines have to change and the code is simpler.
- Using suggested changes to fix lint errors in the generated files instead of disabling linter.

**Comment by ryanofsky** [comment]
@purpleKarrot Do you want to follow up to review comments with https://github.com/bitcoin-core/libmultiprocess/pull/165#pullrequestreview-2672482311? If not, I can merge this is as-is and make other changes in a new PR, or just cherry-pick changes from here into a new PR. You can let me know what your prefer.

Asking because Sjors reported a new clang-tidy error in https://github.com/bitcoin/bitcoin/pull/31802#issuecomment-2858241771 so it looks like some additional fixes may be necessary.

File: include/mp/proxy-types.h [hunk 5]
```diff
@@ -37,20 +37,45 @@ struct StructField
...
-    template<typename A = Accessor, typename... Args> decltype(auto) init(Args&&... args) const { return A::init(this->m_struct, std::forward<Args>(args)...); }
-    template<typename A = Accessor> auto setHas() const -> std::enable_if_t<A::optional> { return A::setHas(m_struct); }
-    template<typename A = Accessor> auto setHas() const -> std::enable_if_t<!A::optional> { }
-    template<typename A = Accessor> auto setWant() const -> std::enable_if_t<A::requested> { return A::setWant(m_struct); }
-    template<typename A = Accessor> auto setWant() const -> std::enable_if_t<!A::requested> { }
-    // clang-format on
+    decltype(auto) get() const { return Accessor::get(this->m_struct); }
+
+    bool has() const {
+      if constexpr (Accessor::optional) {
```
[the remark this answers is not in the document]
Comment (purpleKarrot) [reply include/mp/proxy-types.h:43]: > maybe use clang-format

Would be great if there was a `.clang-format` file.

File: include/mp/proxy-types.h (hunk 2 above)
Comment (purpleKarrot) [reply include/mp/proxy-types.h:395]: > That way the indentation of the code inside the lambda would not have to change

It does. Using the lambda directly has no effect on the number of `{` and hence the indentation.
Also, running `git clang-format` after trying that completely borked the formatting due to no `.clang-format`.

I prefer passing lambda expression to functions directly **iff** the expression is small and it is the last function argument. Here, the lambda expression is complex and it is not the last function argument. Giving it a name results in longer, but more readable code.

**Comment by purpleKarrot** [comment]
@ryanofsky, I dropped the commit that disables linting generated files and extended commit messages.

File: include/mp/proxy-types.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (ryanofsky) [reply include/mp/proxy-types.h:43]: re: https://github.com/bitcoin-core/libmultiprocess/pull/165#discussion_r1988218446

Note: Spacing is still not consistent, but should be fine to reformat later.

File: src/mp/gen.cpp (hunk 4 above)
Comment (ryanofsky) [reply src/mp/gen.cpp:218]: re: https://github.com/bitcoin-core/libmultiprocess/pull/165#discussion_r1988281155

Thanks for the update. From https://cirrus-ci.com/task/6187773452877824?logs=ci#L4758, it seems like clang-tidy error triggering this just looks like: `warning: use a ranges version of this algorithm [modernize-use-ranges]`

**Review by ryanofsky — APPROVED** [review]
Code review ACK aa19285303fff8db9bf8d53491d8a6e6e1617397

Looks good! Will probably merge shortly. Only changes since last review were dropping the SKIP_LINTING commit (764128a1f7bf84fa7713d1c80a1f6b647dfe8a1e) and now describing the clang-tidy errors that are fixed in commit messages.

Note: without SKIP_LINTING commit probably will want to follow up with code generator diff posted at https://github.com/bitcoin-core/libmultiprocess/pull/165#discussion_r1988211338
